name: 'Monorepolyser'
description: 'Awesome set of tools and validators for your yarn monorepo'
icon: activity
inputs:
  check-dependencies:
    description: 'Whether the github action will check the monorepo dependencies integrity or not'
    required: false
    default: false
  ignore-workspaces:
    description: 'List of workspaces separated by comma that will be ignored during the execution of this action'
    required: false
    default: ''
  include-main-package-json:
    description: 'Whether the main package json of the repository should be considered for the integrity check or not'
    required: false
    default: true
  only-warn:
    description: 'Whether this action should only throw a warning or an error'
    required: false
    default: false
  impact-analysis:
    description: 'Whether this action should check the impact of the PRs changes or not'
    required: false
    default: false
  high-impact-threshold:
    description: 'Percentage of packages impacted that determines that the PR has a high impact'
    required: false
    default: 60
  on-high-impact:
    description: 'Action to be executed on high impact PR. It can be "comment", "add-labels" or multiple actions, separating them by a comma'
    required: false
    default: 'comment'
  dependencies-to-ignore:
    description: 'Dependencies names that will be ignore from the analysis, separating them by a comma'
    required: false
    default: ''
  high-impact-labels:
    description: 'Labels to be added (separated by a comma) if the PR has a high impact'
    required: false
    default: ''
  verbose:
    description: 'Whether this action logs the results of its analysis or not. It can be "comment" or "logs"'
    required: false
    default: false
  high-impact-packages-regexp:
    description: 'Regexp that determines which packages should be consider as high impact, no matter the impact analysis'
    required: false
    default: null
runs:
  using: 'node12'
  main: 'packages/ga-monorepolyser/dist/index.js' 
