name: Monorepo Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  check-dependencies:	
    runs-on: ubuntu-latest	
    name: Check dependencies integrity	
    steps:		
      - name: Checkout	
        uses: actions/checkout@v2	
      - name: Check dependencies
        uses: ./
        with:
          check-dependencies: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  impact-analysis:	
    runs-on: ubuntu-latest	
    name: Check impact analysis	
    steps:		
      - name: Checkout	
        uses: actions/checkout@v2	
      - name: Check impact
        uses: ./
        with:
          impact-analysis: true
          high-impact-threshold: 50
          on-high-impact: 'comment,add-labels'
          high-impact-labels: 'high-impact'
          verbose: 'logs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}